//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeStormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        public int EventDetailId { get; set; }
        public long Id { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    }
}
