//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeStormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Text { get; set; }
        public string RecType { get; set; }
        public long EventLength { get; set; }
        public int EventPid { get; set; }
        public string UserId { get; set; }
        public string Color { get; set; }
        public long Id { get; set; }
    }
}
