//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeStormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int MessageId { get; set; }
        public string Message { get; set; }
        public string ReceiverId { get; set; }
        public string SenderId { get; set; }
        public string Status { get; set; }
        public System.DateTime CDate { get; set; }
    }
}
