//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeStormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int ProfileId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Id { get; set; }
        public string ImageUrl { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Location { get; set; }
        public string Mobile { get; set; }
        public string Profession { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string AboutMe { get; set; }
        public string Interests { get; set; }
    }
}
