// <auto-generated />
namespace CodeStormScheduler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class alterlatlngdatatypedecimal107 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterlatlngdatatypedecimal107));
        
        string IMigrationMetadata.Id
        {
            get { return "201507102026418_alter lat lng data type(decimal(10,7))"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
